CREATE TABLE LAST_CORE_INFO  (SK_DATE VARCHAR(8) , IDENTITY_NUM VARCHAR(32) ,LEVEL VARCHAR(32),UPDATE_NO VARCHAR(32),UPDATE_BY VARCHAR(32),UPDATE_ORG VARCHAR(100),UPDATE_SUB VARCHAR(100));
create index idx_LAST_CORE_INFO_1 on LAST_CORE_INFO(IDENTITY_NUM);
CREATE TABLE CUR_CORE_INFO  (SK_DATE VARCHAR(8) , IDENTITY_NUM VARCHAR(32) ,LEVEL VARCHAR(32),UPDATE_NO VARCHAR(32),UPDATE_BY VARCHAR(32),UPDATE_ORG VARCHAR(100),UPDATE_SUB VARCHAR(100));
create index idx_CUR_CORE_INFO_1 on CUR_CORE_INFO(IDENTITY_NUM);

